title: "Jake HONG | Data Analyst & AI Practitioner"
description: "Personal job-seeking website showcasing skills, projects, and resume."

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true   # 先关掉，后面可以再开

author:
  name: "Jake HONG ZEHAO"
  bio: "MSc in Artificial Intelligence and Business Analytics | Passionate about turning data into actionable insights."
  #avatar: "/assets/images/avatar.jpg"   # 把你的照片放进去（推荐 300x300）
  location: "Hong Kong"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:jakehomeshao@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/jake-hong-hk"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Jake3-hub"

search: true
