title: "Jake HONG ZEHAO | Data Analyst & AI Practitioner"
description: "Personal job-seeking website showcasing skills, projects, and resume."

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false   # 先关掉，后面可以再开

search: true
